'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UniConverter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CMDCode-help V1.2.0.6 (2019-07-10 By MineEric64)
        '''
        '''/help - Showing How To Use Command. It shows the Commands to you.
        '''/? - Same as &apos;/help&apos;
        '''/clear - Clear Text.
        '''/del &lt;WName&gt; - Delete File/Directory named &lt;WName&gt;.
        '''/exists &lt;WName&gt; - Exists File/Directory named &lt;WName&gt;. Showing As Boolean.
        '''&lt;WName&gt; Lists: Workspace, abl_proj (Ableton Project File), sounds, keySound (Sound Mapping File), CoLED (LED Files), keyLED (UniPack LED Files), info (UniPack Information), ksTmp (Tempoary keySound), KeyTracks (LED KeyTr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CMDCode_help() As String
            Get
                Return ResourceManager.GetString("CMDCode-help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FLIP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FLIP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PExpY2Vuc2VOYW1lPSJEZXZlbG9wZXIgTW9kZSIgTGljZW5zZURldmVsb3Blcj0iTWluZUVyaWM2NCIgUHJvZ3JhbTJ1c2VMaWNlbnNlPSJVbmlDb252ZXJ0ZXIiIExpY2Vuc2VDcmVhdGVEYXRlPSIyMDE5LTA3LTEwLTEzLTQ2IiBFeHBpcmVkRGF0ZT0iMjAyNC0wNy0xMC0xMy00NiI+
        '''
        '''//This is UniConverter&apos;s Developer Mode License.
        '''- UniConverter ⓒ 2018~2019 최에릭 (MineEric64) All Rights Reserved..
        '''</summary>
        Friend ReadOnly Property License_DeveloperMode() As String
            Get
                Return ResourceManager.GetString("License_DeveloperMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PExpY2Vuc2VOYW1lPSJHcmVhdEV4IE1vZGUiIExpY2Vuc2VEZXZlbG9wZXI9Ik1pbmVFcmljNjQiIFByb2dyYW0ydXNlTGljZW5zZT0iVW5pQ29udmVydGVyIiBMaWNlbnNlQ3JlYXRlRGF0ZT0iMjAxOS0wNy0xMC0xMy01MCIgRXhwaXJlZERhdGU9IjIwMjQtMDctMTAtMTMtNTAiPg==
        '''
        '''//This is UniConverter&apos;s GreatEx Mode License.
        '''- UniConverter ⓒ 2018~2019 최에릭 (MineEric64) All Rights Reserved..
        '''</summary>
        Friend ReadOnly Property License_GreatExMode() As String
            Get
                Return ResourceManager.GetString("License_GreatExMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to o 3 4 a 37
        '''o 4 4 a 37
        '''o 4 5 a 37
        '''o 4 6 a 37
        '''o 5 3 a 37
        '''o 5 4 a 37
        '''o 5 5 a 37
        '''o 6 5 a 37
        '''d 40
        '''o 3 3 a 37
        '''o 3 4 a 37
        '''o 3 5 a 37
        '''o 3 6 a 37
        '''o 4 3 a 37
        '''o 4 4 a 37
        '''o 4 5 a 37
        '''o 4 6 a 37
        '''o 5 3 a 37
        '''o 5 4 a 37
        '''o 5 5 a 37
        '''o 5 6 a 37
        '''o 6 3 a 37
        '''o 6 4 a 37
        '''o 6 5 a 37
        '''o 6 6 a 37
        '''d 40
        '''o 2 5 a 37
        '''o 2 6 a 37
        '''o 3 2 a 37
        '''o 3 3 a 37
        '''o 3 4 a 11
        '''o 3 5 a 37
        '''o 3 6 a 37
        '''o 4 2 a 37
        '''o 4 3 a 37
        '''o 4 4 a 11
        '''o 4 5 a 11
        '''o 4 6 a 11
        '''o 5 3 a 11
        '''o 5 4 a 11
        '''o 5 5 a 11
        '''o 5 6 a 37
        '''o 5 7 a 37
        '''o 6 3 a  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SuperLightText() As String
            Get
                Return ResourceManager.GetString("SuperLightText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UniConverter_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UniConverter_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UniConverter_New_Intro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UniConverter_New_Intro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property UniConverter_New_Intro_Video() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("UniConverter_New_Intro_Video", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property UniConverter_New_Loading() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("UniConverter_New_Loading", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UniConverter_New_Real_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UniConverter_New_Real_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UniConverterV2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UniConverterV2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Unipad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Unipad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
