'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'     런타임 버전:4.0.30319.42000
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    '클래스에서 자동으로 생성되었습니다.
    '멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    '다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    '''<summary>
    '''  지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UniConverter_Project.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        '''  재정의합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  CMDCode-help V1.0.0.2 (2019-03-30 By MineEric64)
        '''
        '''/help - Showing How To Use Command. It shows the Commands to you.
        '''/? - Same as &apos;/help&apos;
        '''/clear - Clear Text.
        '''/del &lt;Name&gt; - Delete File/Directory named &lt;Name&gt;.
        '''/exists &lt;WName&gt; - Exists File/Directory named &lt;Name&gt;. Showing As Boolean.
        '''&lt;WName&gt; Lists: Workspace, abl_proj (Ableton Project File), sounds, CoLED (LED Files), keyLED (UniPack LED Files), info (UniPack Information), ksTmp.txt (Tempoary keySound), KeyTracks.xml (LED KeyTracks)
        '''
        '''/enable &lt;ModeName[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Friend ReadOnly Property CMDCode_help() As String
            Get
                Return ResourceManager.GetString("CMDCode-help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  RGltIGN1ckZpbGUgQXMgU3RyaW5nID0gIlNvdXJjZXNcRGV2ZWxvcGVyTW9kZS51bmkiDQoNCiAgICAgICAgSWYgRmlsZS5FeGlzdHMoY3VyRmlsZSkgVGhlbg0KICAgICAgICAgICAgRGV2ZWxvcGVyVG9vbFN0cmlwTWVudUl0ZW0uVmlzaWJsZSA9IFRydWUNCiAgICAgICAgICAgIERldmVsb3BlclRvb2xTdHJpcE1lbnVJdGVtLkVuYWJsZWQgPSBUcnVlDQogICAgICAgIEVuZCBJZg0KCQkNCgkJJ0RldmVsb3BlclRvb2xTdHJpcE1lbnVJdGVtDQoJCURldmVsb3Blck1vZGUuU2hvdygpDQoJCQ0KCQknSW5mby52YiAtIE1vZEUNCgkJSWYgTW9kZUUuVGV4dCA9ICJVbmlDb252ZXJ0ZXJQcm9qZWN0X0RldmVsb3Blck1vZGUiIFRoZW4NCiAgICAgICAgICAgIElmIERpcihjdXJG[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Friend ReadOnly Property LicenseText() As String
            Get
                Return ResourceManager.GetString("LicenseText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property UniConverterV2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UniConverterV2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Unipad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Unipad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
